### ISSUE TITLE
Disable Warning Credential cache name malformed

### ISSUE THREAD

**Issue by Bleala** [clhedrick/kerberos#2]
Hello there!

I started to use the pam-fixcc module, because of the GSSAPI ssh authentication problem and now everything is working as expected.

But i have one "problem": I'm having two group which can use sudo, one has to use a password the other one not (NOPASSWD). 
When someone from the nopasswd group does a switch do root with sudo-i, the following warning is displayed: `Credential cache name malformed`. 

Is there a way to disable this message?

**Comment by clhedrick** [comment]
I'll take a look
________________________________
From: Bleala ***@***.***>
Sent: Friday, May 6, 2022 6:12 AM
To: clhedrick/kerberos ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [clhedrick/kerberos] Disable Warning Credential cache name malformed (Issue #2)


Hello there!

I started to use the pam-fixcc module, because of the GSSAPI ssh authentication problem and now everything is working as expected.

But i have one "problem": I'm having two group which can use sudo, one has to use a password the other one not (NOPASSWD).
When someone from the nopasswd group does a switch do root with sudo-i, the following warning is displayed: Credential cache name malformed.

Is there a way to disable this message?

**Comment by clhedrick** [comment]
I've fixed it. It was a definite bug.

However pam-fixcc is really intended to fix a problem caused by sshd. It puts the credentials the wrong place. I'd be inclined to put the call to this module in the pam ssh configuration file, not common-session. Then it wouldn't be called for sudo. I don't think it has a useful function other than for sshd. But if you need it for things other than sshd, the error message should now be fixed.

**Comment by clhedrick** [comment]
fixed
